### ISSUE TITLE
test

### ISSUE THREAD

**Issue by zzchuman** [GuillaumeDMMarion/traffic-lights#1]
I run your program on my local windows,but it appears:
![image](https://user-images.githubusercontent.com/38434094/64782934-0f9a6500-d599-11e9-9691-60a58f71ff1f.png)
I know thers is rl_ and no rl. So, could you tell me the path、

**Comment by guillaume-marion** [comment]
Two years late, but should be fixed with the adapted folder structure, i.e. _rl repackaged in rlc.
